name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project chromium
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # - name: Setup Pages
    #   uses: actions/configure-pages@v2
    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v1
    #   with:
    #     path: playwright-report/
    # - name: Deploy to Github Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v1
    
    - name: Publish HTML report to testresults.marcusfelling.com
      if: always() # We want this to always run, even if test fail prior to this step running
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report/ # This is where index.html will be output
        keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
        user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
        user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
